version: "3.8"
services:
  app:
    build:
      args:
        user: jack
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: z-blog
    container_name: z-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - z

  db:
    image: mysql:latest
    container_name: z-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    working_dir: /var/www/
    ports:
      - 3307:3306
    volumes:
      - ./:/var/www
    networks:
      - z

  nginx:
    image: nginx:1.17-alpine
    container_name: z-nginx
    restart: unless-stopped
    ports:
      - 80:80
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - z

networks:
  z:
    driver: bridge
